#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
makeType=${1:-libso}
set -x 

wclean ./chemistryModel
wclean ./reactionThermo
wclean ./basic
wclean ./specie

#------------------------------------------------------------------------------
